### ISSUE TITLE
Got some error messages (related to the physics example) trying to build it.

### ISSUE THREAD

**Issue by doYourCode** [bmdub/RayTracingInDotNet#2]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0535	'Physics.DemoNarrowPhaseCallbacks' does not implement interface member 'INarrowPhaseCallbacks.AllowContactGeneration(int, CollidableReference, CollidableReference, ref float)'	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	178	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0425	The constraints for type parameter 'TManifold' of method 'Physics.DemoNarrowPhaseCallbacks.ConfigureContactManifold<TManifold>(int, CollidablePair, ref TManifold, out PairMaterialProperties)' must match the constraints for type parameter 'TManifold' of interface method 'INarrowPhaseCallbacks.ConfigureContactManifold<TManifold>(int, CollidablePair, ref TManifold, out PairMaterialProperties)'. Consider using an explicit interface implementation instead.	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	201	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0535	'Physics.DemoPoseIntegratorCallbacks' does not implement interface member 'IPoseIntegratorCallbacks.IntegrateVelocity(Vector<int>, Vector3Wide, QuaternionWide, BodyInertiaWide, Vector<int>, int, Vector<float>, ref BodyVelocityWide)'	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	221	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0535	'Physics.DemoPoseIntegratorCallbacks' does not implement interface member 'IPoseIntegratorCallbacks.AllowSubstepsForUnconstrainedBodies'	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	221	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0535	'Physics.DemoPoseIntegratorCallbacks' does not implement interface member 'IPoseIntegratorCallbacks.IntegrateVelocityForKinematics'	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	221	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0535	'Physics.SimpleThreadDispatcher' does not implement interface member 'IThreadDispatcher.DispatchWorkers(Action<int>, int)'	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	263	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0246	The type or namespace name 'PositionFirstTimestepper' could not be found (are you missing a using directive or an assembly reference?)	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	46	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS1503	Argument 2: cannot convert from 'BepuPhysics.Collidables.CollidableDescription' to 'BepuPhysics.Collidables.TypedIndex'	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	57	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS1501	No overload for method 'ComputeInertia' takes 2 arguments	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\Scene\Physics.cs	64	Active	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB3073	The command ""../ShaderCompiler/bin/Release/net5.0/ShaderCompiler.exe" "D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\/" "D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\bin\Release\net6.0\/assets/shaders/"" exited with code 3.	RayTracingInDotNet	D:\Repos\Cpp\RayTracingInDotNet\RayTracingInDotNet\RayTracingInDotNet.csproj	101

**Comment by bmdub** [comment]
Hello,

I cannot reproduce these errors as-is.  However, it looks like these errors appear after upgrading the BepuPhysics package to 2.4.0.

I don't currently have the free time to bump packages and resolve issues in the process; however I'd gladly accept a PR to do so.

Thanks!
